### ISSUE TITLE
Store hasn’t input

### ISSUE THREAD

**Issue by alobanov11** [ww-tech/lasso#27]
Hello. This framework really cool.
I used it for one of my pet projects and there was one problem which I couldn't handle.

When you want to link output with input another module in the flow, you can't:

```
let firstScreen = FirstScreenModule.createScreen()
.
.
.
let secondScreen = SecondScreen.createScreen()

secondScreen.observeOutput { [weak self] output in
  switch output {
  case .didPressButton:
    // I want to send action to firstScreen, so
    // firstScreen.dispatchInputAction(.activate)
  }
}
```

Can you explain me how I should handle it?

**Comment by g-mark** [comment]
Hi Anton,

Glad you're liking the framework!

I think if you hang on to the `Store` of the first screen you'll have better luck.  A `Screen` is really meant to be an ephemeral type, that's used to make it easier to work with the store & view controller.  You don't want to hang on to `Screen` values - it could create a reference cycle.

Here's a way you could do what you want in a `Flow`:
```swift
final class MyFlow: Flow<NoOutputFlow> {

  private weak var firstScreenStore: FirstScreenModule.Store?

  override func createInitialController() -> UIViewController {
    FirstScreenModule
      .createScreen()
      .observeOutput { [weak self] output in
        switch output {
        case .something: self?.showSecondScreen()
        }
      }
      .captureStore(as: &firstScreenStore)
      .controller
  }

  private func showSecondScreen() {
    SecondScreenModule
      .createScreen()
      .observeOutput { [weak self] output in
        switch output {
        case .didPressButton:
          firstScreenStore?.dispatchAction(.activate)
        }
      }
      .place(as: nextPresentedInFlow)
  }

}
```

This assumes that the first & second screen are really quite separate in terms of their models.  If, however first & second were presenting subsets of the same model (e.g., parts one & two of a form that is sent once both are complete), then you would want to create a different setup.  I can show you what I mean if that's applicable.
